### ISSUE TITLE
"Known" button obscured in mobile version

### ISSUE THREAD

**Issue by lucasrodwell** [linanwx/aosr#12]
Hello,

Great useful app, just one issue makes it a little less than perfect, that the "known" button is obscured by the menu at the bottom of the page. Scrolling does not get to the bottom of the page. This is the case on two of my mobile phones, on Android 9 and Android 7, See screenshots :

![iTel A36 Android 9](https://user-images.githubusercontent.com/51288944/224536458-fe440920-f8d4-48cb-b5b3-79096a59c4ed.png)

![Sony Xperia Z5 Android 7](https://user-images.githubusercontent.com/51288944/224536487-00be82e5-d883-44ca-b8f2-71a2690a7954.png)

**Comment by linanwx** [comment]
I have updated to version 1.0.14 and fixed this issue. Now the scrolling logic of the list refers to Obsidian's design, where the last line of content can be scrolled to the middle of the page.

**Comment by lucasrodwell** [comment]
Thanks!
