### ISSUE TITLE
Add deck as a file separately 

### ISSUE THREAD

**Issue by adrianoresende** [linanwx/aosr#13]
I think showing the cards separately and not the whole cards on Obsidian is more organized.

**Comment by linanwx** [comment]
I understand that the deck function is very important for users. However, due to my current commitments with exams and the need to achieve satisfactory scores, I'm sorry to say that it will still take some time to complete this function.

**Comment by linanwx** [comment]
I have already implemented the Deck functionality and released it. With this feature, you can customize your own Deck and make it contain only the content of specific paths. I hope this release won't be too late.
