### ISSUE TITLE
tts example?

### ISSUE THREAD

**Issue by huachuman** [linanwx/aosr#14]
I'm curious what you would put as a tts url. I'm not sure how to find those... mostly what I can find is free online tools that record audio through the broswer or whatnot. Is there an API I don't know about?

**Comment by linanwx** [comment]
Personally, I use Youdao's pronunciation, which only supports English. You can access it at [http://dict.youdao.com/dictvoice?type=0&audio=%s](http://dict.youdao.com/dictvoice?type=0&audio=%25s)
