### ISSUE TITLE
Exclusion of files or folders

### ISSUE THREAD

**Issue by calimbrasti94** [linanwx/aosr#16]
Congratulations on the plugin. The option to exclude some files or folders would be useful.

**Comment by linanwx** [comment]
Thanks for your suggestion. I will work on developing the deck function and plan to include it in future updates.

**Comment by linanwx** [comment]
I have already implemented the Deck functionality and released it. You can use the Deck feature to exclude the paths of any cards you don't want to include while not affecting the review of all your original cards.
