### ISSUE TITLE
Feature to review decks based on tags

### ISSUE THREAD

**Issue by ddrous** [linanwx/aosr#18]
The Spaced Repetition plugin was not working for me, so I switched to this one. It is the best decision I've made since joining Obsidian.

The only feature that I think is missing is the ability to review decks based on tags. For example, if I add the yaml formatter below to my Markdown file
```
---
tags: mathematics
--- 
```
then the Aosr plugin should identify it and propose that I only review decks in files that are tagged with `mathematics`. This would allow for much more targeted and efficient studies.

Thanks again for the great work.

**Comment by linanwx** [comment]
Thank you for your feedback. I have added recognition for 'tags' in the 'frontmatter' to the Deck feature in Aosr. By copying and pasting the following text into your notes, you should be able to see a filtered Deck of specific Flashcards.

``````
```aosr-deck-config
{
	"rule": {
		"conditions": {
			"all": [{
				"fact": "file",
				"path": "$.tags",
				"operator": "regexMatch",
				"value": "mathematics"
			}]
		},
		"event": {
			"type": "match"
		}
	}
}
```
``````

**Comment by ddrous** [comment]
@linanwx Thank you for your hard work. Sorry for the typos in my original message. They must have made things harder for you.

So I don't exactly see where I should paste the text into my notes. I tried adding it to the AOSRDATA below
![image](https://github.com/linanwx/aosr/assets/25456859/ca3bcb12-1e60-452d-9b2a-2bcfaf699148)
but I know not to tamper with that data.

I was actually hoping you would come up with a solution that didn't involve adding code to each notes. My thinking was that all a user would have to do was to add tags to the front matter of each note they wanted to review, then Aosr would sort the notes and the review process according to the tags.

All this so that when I click on the Aosr icon wanting to review my notes, I should see something like the mockup below. I can then select a tag and then start reviewing.
![image](https://github.com/linanwx/aosr/assets/25456859/4f92f14a-08b6-43dd-a8f1-0c1e9522f9c1)

I'm looking forward to seeing what you come up with whenever you find the time.
Best

**Comment by linanwx** [comment]
Hi @ddrous ,

Thank you for your interest in the Aosr plugin and for sharing your thoughts and needs. I've carefully considered your requests, and here's my understanding and response:

Regarding pasting text into your notes: I understand that you're looking for a way to interact with the plugin without tampering with the AOSRDATA. Could you please provide more details about what you're trying to achieve? This will help me understand your needs better and possibly come up with a solution.

Regarding the feature to review decks based on tags: I see that you'd like to have the ability to organize and review notes by tags directly from the main interface. While I understand the convenience this might offer, I've designed the plugin to be flexible and adaptable to different users' needs. Some users might prefer organizing by paths, others by tags, etc. Providing preset tags might limit this flexibility. However, I'm open to hearing more about your specific needs and exploring possible solutions that could accommodate them without compromising the overall design.
