### ISSUE TITLE
[Feature] Can record question data in seperate json file?

### ISSUE THREAD

**Issue by xh542428798** [linanwx/aosr#20]
Your plugin was really wonderful, which effectively solve the issue of multiple blank cloze questions in the original plugin. However, there is a problem in the use of automatic encoding to read the question, as it may make the content of notes unreadable. Is there any other way to resolve this issue?
I like Tag Folder and Tag wrangler to organize my tag, but the link of blocks would broken the interface.
![image](https://github.com/linanwx/aosr/assets/49368033/41fb326c-ee5d-49e1-87a8-72cdcb77d436)

What's more, the json data inseted in the last of file also made the note too long:
![image](https://github.com/linanwx/aosr/assets/49368033/b74dce90-a003-4e72-9c93-1eee5859d1b0)

**Comment by xh542428798** [comment]
特别喜欢作者您完善了多空白的完型填空的功能，这个是官方没有的，万分感谢，但是就是感觉卡片数据对原笔记有太大的破坏，是否可以考虑另外一个插件的功能[obsidian-spaced-repetition-recall](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall)，能否取消块引用，把所有数据都单独存放？

**Comment by linanwx** [comment]
Hi @xh542428798,

Thank you for your valuable feedback and kind words about the plugin. I'm currently conceptualizing a solution for independent file storage of review records. For the time being, these records will be temporarily placed at the end of the file.

Once this feature is rolled out, you will have the option in the configuration interface to migrate these data to a separate file. I understand the concerns you've raised, and I'm working diligently to enhance the user experience.

Best regards,
linanwx

**Comment by linanwx** [comment]
感谢你的反馈。我已经发布了1.1.1版本，在这个版本中，数据不会再写入到笔记中了，而是写到独立的db文件中。关于Aosr创建的标签影响到用户标签的问题，目前Aosr的设计需要依赖标签为文本打上唯一标记，从而关联复习进度和用户卡片。我们会继续考虑如何改进这个问题。

Thank you for your feedback. I have released version 1.1.1. In this version, the data will no longer be written into the notes, but into a separate db file. Regarding the issue of Aosr-created tags affecting user tags, the current design of Aosr needs to rely on tags to mark the text uniquely, thereby associating the review progress and user cards. We will continue to consider how to improve this issue.

**Comment by xh542428798** [comment]
> 感谢你的反馈。我已经发布了1.1.1版本，在这个版本中，数据不会再写入到笔记中了，而是写到独立的db文件中。关于Aosr创建的标签影响到用户标签的问题，目前Aosr的设计需要依赖标签为文本打上唯一标记，从而关联复习进度和用户卡片。我们会继续考虑如何改进这个问题。
> 
> Thank you for your feedback. I have released version 1.1.1. In this version, the data will no longer be written into the notes, but into a separate db file. Regarding the issue of Aosr-created tags affecting user tags, the current design of Aosr needs to rely on tags to mark the text uniquely, thereby associating the review progress and user cards. We will continue to consider how to improve this issue.

感谢，转移到db文件夹下已经好很多了，唯一标记您也缩短了，即使在源码模式下也只剩下一个图标了，只是用tag folder还会有多余的标签，大概这是块引用的问题，不过已经属于可以接受的程度了，感谢您的努力。
