### ISSUE TITLE
It is suggested to increase the area that can choose to review

### ISSUE THREAD

**Issue by fireflysss** [linanwx/aosr#22]
Thank you very much for making this plug-in. It may be more convenient to use than ANKI.

In the process of learning, often learn different knowledge. Some are in a hurry, while others are not so anxious. For example, the exam is divided into many subjects. You, the plug-in, cannot set up the review area or folder.

**Comment by fireflysss** [comment]
I am not a programmer, can you provide a few settings without code, thank you very much.

**Comment by fireflysss** [comment]
`
```aosr-deck-config
{
	"rule": {
		"conditions": {
			"all": [{
				"fact": "card",
				"operator": "contains",
				"value": "#KEYWORD",    <-- Replace with the tag you want to filter
				"path": "$.tags"
			}]
		},
		"event": {
			"type": "match"
		}
	}
}
```
`
Using tags to manage is also a good way. But according to your example
I replaced the keyword, but it didn't work.

**Comment by linanwx** [comment]
I'm sorry to hear about the difficulties you're experiencing. I'll consider adding some features to simplify this process.

Regarding the Deck creation code you mentioned, please check the following:

First, this code can be copied into any note; it doesn't have to be a specific one.
Second, make sure the code block starts with ` ```aosr-deck-config ` and ends with ` ``` `, without any extra spaces in between.
Assuming you have a card tagged with #math, like this:

```markdown
#Q
a^2 + b^2 = ? :: c^2 #math
```

The code to filter corresponding cards would be:

```json
{
"rule": {
"conditions": {
"all": [{
"fact": "card",
"operator": "contains",
"value": "#math",
"path": "$.tags"
}]
},
"event": {
"type": "match"
}
}
}
```

Make sure to wrap this code with ` ```aosr-deck-config` and  ` ``` ` .

After you finish editing, move the cursor out of this code block or switch Obsidian to preview mode. You should see this code block correctly transformed into a review interface.


Certainly, you can add the following sentence to your response:



The final note should look something like this:  
![Final Note Example](https://user-images.githubusercontent.com/16589958/255379139-b05aecc8-51f6-40d0-98bc-f07a7ada6221.png)

**Comment by linanwx** [comment]
Suppose you have a folder called `math` containing many notes, each with multiple cards. You can use the following code to review all the notes within the `math` folder:

`````
```aosr-deck-config
{
	"rule": {
		"conditions": {
			"all": [{
				"fact": "card",
				"operator": "regexMatch",
				"value": "math", 
				"path": "$.path"
			}]
		},
		"event": {
			"type": "match"
		}
	}
}
```
`````

**Comment by fireflysss** [comment]
Thank you for your busy reply to me, thank you very much
It turned out that I misunderstood that there must be another label at the same time as #Q. I thought it was to replace #Q and mark it with different labels, such as different examination subjects.
I just tried the path method, which uses directories to distinguish between methods, I think it is very useful.
I hope you will reduce the difficulty of using this plug-in, and more people will like it, obsidian more and more people use this software, and many people who are not programmers are also using it, such as mine.

Best wishes for you

**Comment by linanwx** [comment]
Thank you for your feedback. I will enhance the relevant documentation and explore ways to simplify the process.
