### ISSUE TITLE
[Feature Request] Adjust Card Order in Queue Based on Priority Levels

### ISSUE THREAD

**Issue by jingwangsg** [linanwx/aosr#23]

**Comment by linanwx** [comment]
Thank you for using Aosr and providing valuable feedback.


You can try creating cards with specific tags to distinguish between high-priority and regular cards. For example:

#Q
#highpriority
Card content ...

Then, using Aosr's Deck feature, create a deck in your notes that filters for these tagged cards. This way, you can prioritize reviewing these cards.

Alternatively, you can place these high-priority cards in a specific folder, such as a "highpriority" folder, and then use the Deck feature to filter for these cards.

You can refer to https://github.com/linanwx/aosr#deck-functionality-in-aosr to see how to use the Deck functionality within Aosr.
