### ISSUE TITLE
Can't boot up the plugin

### ISSUE THREAD

**Issue by siainbuletin** [linanwx/aosr#29]
I installed the plugin and something's a little unclear. Should I be using the Spaced Repetition plugin in conjunction or is this plugin standalone? There's no aosr.db file being created in the .obsidian folder, nor does anything appear in the cards view if I write my cards like this.

![image](https://github.com/linanwx/aosr/assets/97026492/2a41c4c6-300d-4434-8e51-c6ff93c08113)

I also tried loading and reloading the plugin, the app, and linting my vault with the linter plugin. Nothing turned up.

Obsidian version: 1.4.16
Plugin on the latest version, downloaded just yesterday

**Comment by linanwx** [comment]
Firstly, only the Aosr plugin needs to be installed, and there's no requirement for additional plugins such as the Spaced Repetition plugin. This plugin operates independently. Secondly, if this is your first time using it, there's no need to be concerned about the aosr.db file as it should be handled internally by the plugin. I noticed that you have formatted your cards with lowercase #q, however, the plugin currently only recognizes uppercase #Q.

Try this:

#Q
physis
?
originea supremă a tuturor celorlalte substanțelor din univers
