### ISSUE TITLE
[BUG] Clicking on Review Icon try to trigger Excalidraw  shortcut

### ISSUE THREAD

**Issue by andrewcrook** [linanwx/aosr#3]
Hi when I click the Review icon I don't get aosr it does something strange with a Excalidraw

<img width="386" alt="image" src="https://user-images.githubusercontent.com/803618/198352385-f5aaa096-a0cc-4d25-bfe9-edd8dbf65286.png">

I also have Key Promoter installed which shows this event.

**Comment by linanwx** [comment]
I will check it.

**Comment by linanwx** [comment]
The problem should have been fixed. If you have any questions, please contact me.
