### ISSUE TITLE
Hide media in answer

### ISSUE THREAD

**Issue by hariangr** [linanwx/aosr#43]
I want to learn guitar chord (Using screenshot of the chord as answer)
Unfortunately aosr seems to only blur the image, and I can still see the chord pattern like this
<img width="453" alt="image" src="https://github.com/linanwx/aosr/assets/18433715/68f649cb-a4ce-47d6-bd62-9cb19d8e8625">

Is it expected behavior? How do I make the answer completely unrecognizeable in preview?

**Comment by linanwx** [comment]
I have resolved this issue by adjusting the blur settings for the media. I hope this helps.
